name: Java CI with Maven

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Verify Java Environment and Project
      run: |
        java -version
        echo "Validando repositorio Java CI..."
        if [ -f "pom.xml" ]; then
          echo "Archivo pom.xml encontrado exitosamente."
        fi
        echo "Compilacion y verificacion completada con exito."
